namespace TownOfUs
{
    public enum CustomRPC
    {
        SetRole = 100,
        SetModifier,
        SetCouple,
        SetAssassin,
        SetTarget,
        SetGATarget,

        SetPhantom,
        CatchPhantom,

        SetHaunter,
        CatchHaunter,

        SetTraitor,
        TraitorSpawn,

        LoveWin,
        GlitchWin,
        JuggernautWin,
        ArsonistWin,
        PhantomWin,
        NobodyWins,
        PlaguebearerWin,
        PestilenceWin,
        WerewolfWin,
        SurvivorOnlyWin,
        VampireWin,

        JanitorClean,
        FixLights,
        EngineerFix,
        SetSwaps,
        Protect,
        AttemptSound,
        Morph,
        Mine,
        Swoop,
        AltruistRevive,
        BarryButton,
        Drag,
        Drop,
        AssassinKill,
        VigilanteKill,
        DoomsayerKill,
        FlashGrenade,
        Alert,
        Remember,
        BaitReport,
        Transport,
        SetUntransportable,
        Mediate,
        Vest,
        GAProtect,
        Blackmail,
        Infect,
        TurnPestilence,
        Disperse,
        Escape,
        Imitate,
        StartImitate,
        Plant,
        Bite,
        Reveal,
        Prosecute,
        Confess,
        Bless,
        Camouflage,
        HunterStalk,
        AbilityTrigger,
        Elect,
        Fortify,
        Hypnotise,
        Jail,
        Collect,
        Retribution,
        Camp,

        BypassKill,
        BypassMultiKill,
        SetMimic,
        RpcResetAnim,
        SetHacked,

        ExecutionerToJester,
        GAToSurv,

        Start,
        SyncCustomSettings,
        FixAnimation,
        SetPos,
        SetSettings,
        
        RemoveAllBodies,
        CheckMurder,

        SubmergedFixOxygen,

        ContentAddition
    }
}
